import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { sanityClient, UrlFor } from '../lib/sanity';
import Link from 'next/link';

const recipesQuery =`*[_type == "recipe"]{
  _id,
  name,
  slug,  
}`;


export default function Home({recipes}) {
  
  return (
    <div>
      <Head>
        <title>Kap's Kitchen </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Kap's Kitchen 🍍</h1>
      <ul className="recipes-list">
        {recipes?.length > 1 &&
          recipes.map((recipe) => (
            
            <li>
              <Link href="/">
                <a>
                  <img  />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  )
}


export async function getStaticProps(){

const recipes = await sanityClient.fetch(recipesQuery)

return{ props: { recipes } };
  
}